### ISSUE TITLE
Use mocks by priority on requests

### ISSUE THREAD

**Issue by morsdyce** [500tech/mimic#133]
Currently all the mocks are used by order of appearance i the data.
So if I have 2 mocks which match to the exact same request, the first mock that appears in the data will be selected.

We need to introduce specificity checks to correctly identify which mock should be used.
In general these are the rules I had in mind:
1. Mocks that use wildcards matching should be prioritized last.
2. Mocks that fit the request exactly should be selected first.

**Comment by ilyagelman** [comment]
Implemented a different UX approach in 2.0
