### ISSUE TITLE
Add an easy way to update a mock from a request

### ISSUE THREAD

**Issue by adamkleingit** [500tech/mimic#153]
Scenario:
I record a bunch of server requests and mock them
After a month a lot of server APIs changed
I want to record them again and **replace** the current mocked requests

Is it possible?

**Comment by morsdyce** [comment]
Need to think on how it's best to do it.
Currently you would just turn off or delete the current mock and run the request again and save the input.

Maybe I could set a flag where it will ignore the _next_ request and let it run normally and then update the mock data from what it received.

In general I'd like to support an auto record feature in the near future.

**Comment by adamkleingit** [comment]
In my mind it was:
If the mocked request is disabled you still try to match the captured
requests by it.
If it matches a disabled request - you show a greyed out M icon in the left
sidebar next to the request
if the user clicks on it you show an "Update Mock" button, instead of a
"Mock" button
If the user clicks on the "Update Mock" button - you copy the new response
data to the mocked request (or navigate to the edit screen with the new
response already updated)

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by adamkleingit** [comment]
Or simpler:
next to each captured request regardless of whether it's mocked or not - we
can have an update mock button, and the user can choose which mocked
request he overrides

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by morsdyce** [comment]
I really like this idea, in general I would only show it on non mocked requests because otherwise I won't have the new response and I can't re run the request.

**Comment by adamkleingit** [comment]
True

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by ilyagelman** [comment]
Implemented in 2.0
