### ISSUE TITLE
Allow to duplicate mocked request

### ISSUE THREAD

**Issue by adamkleingit** [500tech/mimic#155]
Allow to make a copy of the mocked request.
3 options:
- it will make a copy of the request inside the same scenario
or
- it will make a copy of the request inside the same scenario, and take me to the edit screen
or
- it will take me to the edit screen of a new copy, and I can choose scenario / change things - and only when I save it will be added

I think 3rd option is the best

**Comment by morsdyce** [comment]
I like the 3rd option as well, it is also the easiest to implement
