### ISSUE TITLE
Improve console output

### ISSUE THREAD

**Issue by ilyagelman** [500tech/mimic#159]
Currently the console output is very subtle and hides all the important information.

I'd suggest add color coding, think about the content and output the most important information up front without the need to expand the output.

**Comment by morsdyce** [comment]
This is what I aimed for at the beginning, I color coded what I thought was important and collapsed the information that I didn't think is necessary up front.

I'd love to hear what you think is important and what should also be color coded.

**Comment by morsdyce** [comment]
Also check how we can better log to the console on browsers that do not support console.groupCollapsed and do not support console colors.
