### ISSUE TITLE
global paths in nightwatch.json file

### ISSUE THREAD

**Issue by DvirSh** [500tech/mimic#166]
The nightwatch.json file contains references to:
```
/Users/maayan/selenium/
```

**Comment by morsdyce** [comment]
Hi Dvir,

This was done to speed up development of end to end tests to test Mimic, these tests are run locally before releases so they're currently configured to my machine configuration.

Making it run on every machine is on my todo list but on a very low priority for now.

If you want to help out this can be a great first pull request.

Thanks
