### ISSUE TITLE
Add custom status codes support

### ISSUE THREAD

**Issue by liorch88** [500tech/mimic#194]
There should be a way to enter custom http status codes, which do not appear in the constant "status codes" list.
If for example I want to test my error handler for cloudflare's error codes (522, 523, etc) - It cannot be done.

I was thinking of adding Cloudflare's status codes to mimic's status codes list, but it might pollute the list if we add all the unofficial status codes (https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#Unofficial_codes)

So instead maybe there should simply be a way to enter an arbitrary status code.

**Comment by morsdyce** [comment]
This is a use case I didn't think as I thought people will only test against the official HTTP status codes.

We are currently working on the next major version of mimic which actually allows you do exactly that.
In the meantime I'll add the ability to add custom codes to the existing control in the next minor release.

Thanks!

**Comment by liorch88** [comment]
Great, thanks!

**Comment by liorch88** [comment]
There is a small regression now: the autocomplete is not working for the status codes dropdown.
When typing any existing status code (such as: 400) it doesn't find anything and only shows "Add 400?".
Note that typing "4" or "40" does find the statuses, but "400" doesn't.

**Comment by morsdyce** [comment]
Thanks, will look into it.

**Comment by ilyagelman** [comment]
Implemented in 2.0
