### ISSUE TITLE
Failed to migrate

### ISSUE THREAD

**Issue by edDimensi** [500tech/mimic#235]
Hi, i try drop postman file in mimic and get errors.
![image](https://cloud.githubusercontent.com/assets/11390039/24255964/007d15ea-0ff8-11e7-99aa-36bd2c08683b.png)

**Comment by morsdyce** [comment]
Hi @edDimensi 

We currently do not support postman files yet but it is planned for the near future.
I'll make sure we add a check for supported import formats so you can see a proper error message instead of errors in the console.

Thanks!
