### ISSUE TITLE
When duplicating a mock inside the group, the duplicated mock is created outside the mock

### ISSUE THREAD

**Issue by morsdyce** [500tech/mimic#240]
This causes an issue where if the group is high in the list, the duplicate is created but the user doesn't know about it.

Possible solutions:
1. create it in the same group
2. Focus the user on the duplicated mock and scroll to the mock point of view
3. Both

**Comment by a1b4** [comment]
@morsdyce I created the PR #248 to fix this.

**Comment by morsdyce** [comment]
Merged, will be available on next release.

Thanks!
