### ISSUE TITLE
No Other Response Types?

### ISSUE THREAD

**Issue by OmriAharon** [500tech/mimic#247]
Hey, great package!

I'm trying to mock 403, so I pressed "Other..." but nothing happened except a very quick glitch in the UI there.

![image](https://cloud.githubusercontent.com/assets/12033595/26572987/bffb135c-4524-11e7-8f3c-d5f5741b21a1.png)

Am I doing something wrong?

**Comment by morsdyce** [comment]
Hi Omri,

When clicking on other an input should show where you can type the exact status code you want.

![mimic-status-code](https://cloud.githubusercontent.com/assets/1665570/26573980/655a96d0-4528-11e7-90b5-55460731f060.gif)

**Comment by morsdyce** [comment]
Please let me know if that's not how it works for you and the mimic version you are using.

Thanks!

**Comment by OmriAharon** [comment]
Thanks for the quick response!
This is what I'm getting with version 2.0.2 (nothing happens, quick UI glitch not captured in the recording, guess it's too quick):
![mimic](https://cloud.githubusercontent.com/assets/12033595/26574491/400fbd72-452a-11e7-9a14-0d941f881f62.gif)

**Comment by morsdyce** [comment]
Can you please check if it works for you on https://mimic.js.org/
Also if you see any errors in the console?

**Comment by OmriAharon** [comment]
It works there.

In my local env, I have no console errors.

**Comment by OmriAharon** [comment]
I might have caught glimpse of a "Server Error" text or something in the quick UI glitch where the status numbers are.

**Comment by morsdyce** [comment]
If that's the case then it seems there is an issue with the integration of mimic to your application.
Mimic doesn't run inside an iframe so it might be affected by something in your application.

If you can create a example where it fails to open there that would be great, if not I'll have to do some testing and see what can stop it from opening.

**Comment by OmriAharon** [comment]
That's weird... I tried to debug now to see if I can give you some more information but now it works. Can it be that after I entered the link you sent something got fixed somehow?

**Comment by morsdyce** [comment]
No, nothing should have changed, that's odd.

**Comment by OmriAharon** [comment]
Well, as much as I hate leaving loose ends like this, I can't seem to reproduce it anymore, so I guess this could be closed. Thanks for the assistance!

**Comment by morsdyce** [comment]
Ok, let me know if it ever happens again, I'll try investigating on what can cause it.

Thanks for your time 👍
