### ISSUE TITLE
Fails to work with fetch

### ISSUE THREAD

**Issue by maksimsemenov** [500tech/mimic#255]
I have this issue when trying to use mimic with fetch and then parse response to json.

```
fetch('/google_auth')
    .then(response => {
      console.log('response', response);
      return response.json();
    })
    .then(json => console.log('json', json));
```

This is how my mock looks like.
<img width="1599" alt="screen shot 2018-05-16 at 4 49 46 pm" src="https://user-images.githubusercontent.com/3608139/40143356-313dc2bc-5929-11e8-8d85-268928eb0839.png">

This code eventually leads to error:
```
es6.promise.js?e8d6:110 Unhandled promise rejection SyntaxError: Unexpected string in JSON at position 54
```

I'm probably doing something stupid, but I can't figure out why it doesn't work

**Comment by morsdyce** [comment]
The JSON response is invalid so response.json() fails to parse it, you are missing a comma after google_id line. You can test it by pasting the json to https://jsonlint.com/

**Comment by maksimsemenov** [comment]
Ooh, you’re totally right. Sorry. I knebit was something stupid. Thanks a lot

**Comment by morsdyce** [comment]
Hopefully in the near future I'll be able to add JSON validation to the editor which will give feedback on such things.

Happy to help!
