### ISSUE TITLE
create a version of mimic that can be used in non react apps.

### ISSUE THREAD

**Issue by malplayer** [500tech/mimic#258]
I would like a bundled js file that I can  use with require js on non react page

**Comment by morsdyce** [comment]
Hi @malplayer,

Mimic is completely agnostic so it can run regardless of the technology your app is built with.
It should be able to be required in requirejs apps right now as it is built with the UMD pattern.

There might be issues with the main index file of the library, please try requiring `mimic/dist/mimic.js ` instead and let me know if that works for you.

I'll look into this and make sure we can load mimic normally in requireJS apps without resorting to a specific path.

In addition to requiring Mimic in your application you can also include mimic via unpkg CDN:
https://unpkg.com/mimic@2.0.7/dist/mimic.js

Thanks

**Comment by morsdyce** [comment]
It looks like there was an issue where mimic failed to load on environments that do not provide or transform process.env.NODE_ENV which has been fixed in v2.0.8

If you have any further issues please reopen this issue.

Thanks

**Comment by malplayer** [comment]
could you provide a small example on how to do this  i just want to make sure i understand how to do it
