### ISSUE TITLE
Dynamic import semiworking with import('mimic'); but working with require('mimic');.

### ISSUE THREAD

**Issue by mmesar** [500tech/mimic#260]
If I use dynamic import with import('mimic');, mimic is imported and apis are mocked and working but i dont see mimic ui on screen,
If I use dynamic import with require('mimic'); everything working as intended.

![xyz](https://user-images.githubusercontent.com/24696326/43649363-3db57948-973d-11e8-814b-1ba6646b70b6.png)

**Comment by morsdyce** [comment]
Hi @mmesar 

Thanks for reporting this, I've applied a fix which will be available in the next version

**Comment by morsdyce** [comment]
Fixed in v2.0.8
