### ISSUE TITLE
Keep mimic open on refresh

### ISSUE THREAD

**Issue by sagivf** [500tech/mimic#265]
First, great job on this project, I am surperised this project isn't better known.

Question:
Couldn't find a way to keep mimic open  on refresh (like dev tools).

**Comment by morsdyce** [comment]
Hi, first of all thanks for the feedback!

Currently the only way to keep mimic open between refreshes is using remote mode:
https://mimic.js.org/guides/remote.html

Let me know if you need any help with setting it up

**Comment by sagivf** [comment]
Thanks @morsdyce that's a great option. I couldn't get it to work though, opened a different issue.
https://github.com/500tech/mimic/issues/267
