### ISSUE TITLE
Set stopwatch to zero

### ISSUE THREAD

**Issue by adisahar** [500tech/mimic#266]
Seem the stopwatch can't be set to zero. Is it possible to hardcode it into the JSON? I think the stopwatch could use a delay toggle in the settings.

**Comment by morsdyce** [comment]
I assume by stopwatch you mean the request delay before you have a response.
You can change it by exporting and importing the mock.

To do this you will need to do the following:
1. Copy or export to json by right clicking on the mock
![image](https://user-images.githubusercontent.com/1665570/53348622-17a7f580-3924-11e9-9c63-b93bc7040632.png)

2. Change the mock response.delay parameter to 0.
![image](https://user-images.githubusercontent.com/1665570/53348682-327a6a00-3924-11e9-89f3-2b7fc938b103.png)

3. Reimport the file in 1 of 3 ways:
* import using mimic api (https://mimic.readme.io/reference#section-import-jsonstring-)
* import by dragging the file into mimic
* go to the settings screen (small cog on the lower right) and choose import file
![image](https://user-images.githubusercontent.com/1665570/53348852-85ecb800-3924-11e9-914c-852c067fdc41.png)

I'll add in the near future the ability to allow 0 delay for the mocks.

I'm not sure what you mean about the delay toggle, do you mean globally resolving all requests at a certain delay set in the settings screen?

**Comment by YoavSch** [comment]
Start fix it

**Comment by morsdyce** [comment]
Fixed in #286

**Comment by wildeyes** [comment]
was this not published to NPM?
