### ISSUE TITLE
Match dynamic query parameters like dates

### ISSUE THREAD

**Issue by adi518** [500tech/mimic#275]
Is it possible to wildcard dynamic query parameters like date? took me a while to figure out why my mocked request wasn't working. :)

**Comment by morsdyce** [comment]
Hey, It is possible on the url and request body, you can see examples in the provided images.

![image](https://user-images.githubusercontent.com/1665570/70642407-d5983800-1c47-11ea-9eb6-f2f83ec96bdc.png)
           
![image](https://user-images.githubusercontent.com/1665570/70642422-daf58280-1c47-11ea-9da1-de4411d6c2c5.png)

![image](https://user-images.githubusercontent.com/1665570/70642446-e21c9080-1c47-11ea-8ede-0c747b2e827d.png)
